//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceNovel.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliceNovel.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Canncel_ {
            get {
                return ResourceManager.GetString("Alert (Canncel)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Confirm に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Confirm_ {
            get {
                return ResourceManager.GetString("Alert (Confirm)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save data found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Load1_ {
            get {
                return ResourceManager.GetString("Alert (Load1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to load the save data? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Load2_ {
            get {
                return ResourceManager.GetString("Alert (Load2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Load3_ {
            get {
                return ResourceManager.GetString("Alert (Load3)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   From the begining に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Load4_ {
            get {
                return ResourceManager.GetString("Alert (Load4)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load failed, load from the beginning. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Load5_ {
            get {
                return ResourceManager.GetString("Alert (Load5)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reboot に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Reboot_ {
            get {
                return ResourceManager.GetString("Alert (Reboot)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you want to reboot the application?
        ///(If the game runs, you have to save it before reboot.) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__RebootDescriptions_ {
            get {
                return ResourceManager.GetString("Alert (RebootDescriptions)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Save1_ {
            get {
                return ResourceManager.GetString("Alert (Save1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Successed to save the game information. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Save2_ {
            get {
                return ResourceManager.GetString("Alert (Save2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Warning に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Warn1_ {
            get {
                return ResourceManager.GetString("Alert (Warn1)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The file is old type, and this is out of support. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Alert__Warn2_ {
            get {
                return ResourceManager.GetString("Alert (Warn2)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Alice Novel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Overwrite Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button1__Tip_ {
            get {
                return ResourceManager.GetString("Button1 (Tip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button2 {
            get {
                return ResourceManager.GetString("Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reshow with touching the display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button2__Tip_ {
            get {
                return ResourceManager.GetString("Button2 (Tip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Load に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button5 {
            get {
                return ResourceManager.GetString("Button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Read game file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button5__Tip_ {
            get {
                return ResourceManager.GetString("Button5 (Tip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Dark-mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorTheme__Dark_ {
            get {
                return ResourceManager.GetString("ColorTheme (Dark)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The color theme of application に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorTheme__Description_ {
            get {
                return ResourceManager.GetString("ColorTheme (Description)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Light-mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ColorTheme__Light_ {
            get {
                return ResourceManager.GetString("ColorTheme (Light)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Language Setting (Necessary to Reboot) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LanguageSetting {
            get {
                return ResourceManager.GetString("LanguageSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s Play the Game! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string SettingsPage_Title {
            get {
                return ResourceManager.GetString("SettingsPage Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab1 {
            get {
                return ResourceManager.GetString("Tab1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Settings に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Tab2 {
            get {
                return ResourceManager.GetString("Tab2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please read Alice Novel game (.anproj file). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBox__Default_ {
            get {
                return ResourceManager.GetString("TextBox (Default)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reshow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem1__Reshow_ {
            get {
                return ResourceManager.GetString("ToolbarItem1 (Reshow)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit the Game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3 {
            get {
                return ResourceManager.GetString("ToolbarItem3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3__Exit_ {
            get {
                return ResourceManager.GetString("ToolbarItem3 (Exit)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   No save and Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3__only_Exit_ {
            get {
                return ResourceManager.GetString("ToolbarItem3 (only Exit)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save and Exit に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3__Save_and_Exit_ {
            get {
                return ResourceManager.GetString("ToolbarItem3 (Save and Exit)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do you save the game? に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3__Save_or_not_ {
            get {
                return ResourceManager.GetString("ToolbarItem3 (Save or not)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Close currently game に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ToolbarItem3__Tip_ {
            get {
                return ResourceManager.GetString("ToolbarItem3 (Tip)", resourceCulture);
            }
        }
    }
}
