//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AliceNovel.Resources.Strings {
    using System;

    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AliceNovel.Resources.Strings.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Alice Novel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Application_Name {
            get {
                return ResourceManager.GetString("Application Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button1 {
            get {
                return ResourceManager.GetString("Button1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save with onwrite に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button1__Tip_ {
            get {
                return ResourceManager.GetString("Button1 (Tip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Hide UI に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button2 {
            get {
                return ResourceManager.GetString("Button2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reshow with touching the display に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button2__Tip_ {
            get {
                return ResourceManager.GetString("Button2 (Tip)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Road game file に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string Button5 {
            get {
                return ResourceManager.GetString("Button5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Let&apos;s Play the Game! に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MainPage_Title {
            get {
                return ResourceManager.GetString("MainPage Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please read Alice Novel game (.anproj file). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TextBox__Default_ {
            get {
                return ResourceManager.GetString("TextBox (Default)", resourceCulture);
            }
        }
    }
}
